# Generated by Django 3.1.1 on 2020-09-23 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_jwt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='token',
            name='token',
        ),
        migrations.RemoveConstraint(
            model_name='token',
            name='refresh',
        ),
        migrations.AddConstraint(
            model_name='token',
            constraint=models.UniqueConstraint(fields=('access_token',), name='token'),
        ),
        migrations.AddConstraint(
            model_name='token',
            constraint=models.UniqueConstraint(fields=('refresh_token',), name='refresh'),
        ),
    ]
